dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - cv2
    - tkinter
    - PIL
    - shutil
    - tkinter
    - skimage
    - tensorflow
    - keras
